baseurl = "https://www.mehmetcanhakli.com/"
title = "Mehmet Can Haklı"
author = "Mehmet Can Haklı"
canonifyurls = true
languagecode = "en-US"
copyright = "GNU General Public License v3.0"
enableRobotsTXT = true
log = true
logFile = "hugo.log"
verboseLog = true
metaDataFormat = "toml"
verbose = true

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Mehmet Can Haklı"
  disableWebFonts = false
[permalinks]
  post = "/:slug/"
  page = "/:slug/"
[sitemap]
  changefreq = "weekly"
  priority = 0.5

[menu]

  [[menu.main]]
      name = "About Me"
      url  = "/about/"
  [[menu.main]]
      name = "Projects"
      url  = "/projects/"
  [[menu.main]]
      name = "Resume"
      url  = "/resume/"
  [[menu.main]]
      name = "Random Facts"
      url  = "/randomfacts/"
